name: sample
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

#----Packages----#
dependencies:
  flutter:
    sdk: flutter

#----Utility Packages----#
  # icons
#  flutter_icons: ^1.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  url_launcher: ^6.0.0
  intl: ^0.17.0
  http: ^0.13.3
  get_storage: ^2.0.3
  logger: ^2.2.0
  top_snackbar_flutter: ^3.1.0

#---- Packages End----#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#----Local Assets----#
assets:
  - assets/icons/brands/
  - assets/images
  - assets/logos

#----Local Fonts----#
fonts:
  - family: Poppins
    fonts:
      - assets: assets/fonts/Poppins-Light.ttf
        weight: 300

